services:
  - type: web
    name: shree-swami-samarth-mess
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: GEMINI_API_KEY
        sync: false
      - key: APP_URL
        sync: false
